const express=require('express');
const path=require('path');
const app=express();
const PORT=process.env.PORT||10000;
app.use(express.json());
app.use(express.static(path.join(__dirname,'public')));
app.get('/health',(req,res)=>res.json({status:'ok',app:'LilianTech'}));
app.get('/api/surveys',(req,res)=>res.sendFile(path.join(__dirname,'data','surveys.json')));
app.get('/api/providers',(req,res)=>res.sendFile(path.join(__dirname,'data','providers.json')));
app.listen(PORT,()=>console.log(`LilianTech running on ${PORT}`));
